server:
  port: 8081
  servlet:
    context-path: /order
#  servlet:
#    session:
#      cookie:
#        name: UISESSIONCOUPON

security:
  oauth2:
    client:
      client-id: app
      client-secret: 12345
      access-token-uri: http://localhost:8080/auth/oauth/token
      user-authorization-uri: http://localhost:8080/auth/oauth/authorize
    resource:
      userInfoUri: http://localhost:8080/auth/user