server:
  port: 8081
  servlet:
    session:
      cookie:
        name: UISESSIONCOUPON
security:
  oauth2:
    client:
      client-id: app
      client-secret: 123456
      access-token-uri: http://localhost:8080/oauth/token
      user-authorization-uri: http://localhost:8080/oauth/authorize
    resource:
      user-info-uri: http://localhost:8080/user